apiVersion: v1
kind: Service
metadata:
  name: unauthenticated
  namespace: registry
spec:
  selector:
    app: registry
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: https-local
    port: 5000
    targetPort: 443
